name: Unit Test Workflow

on:
  pull_request:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-dependencies
        name: Setup dependencies

      - run: npm run test -- --coverage
